### ISSUE TITLE
Can the code be compiled directly?

### ISSUE THREAD

**Issue by duxingg** [JefferyLi0903/MMC#2]

**Comment by duxingg** [comment]
Why am I burning code to the board, but it doesn't work properly, and there are problems debugging?

**Comment by JefferyLi0903** [comment]
The instruction path in a source code file should be modified because it doesn't use a relative path. Also make sure the header file is not set to the simulation mode.

**Comment by JefferyLi0903** [comment]
<img width="861" alt="image" src="https://user-images.githubusercontent.com/31439283/187016479-332cf323-ee21-45af-88e8-d9a37f05c391.png">
The path in the fifth line should be modified.
